### ISSUE TITLE
Screeners and demo

### ISSUE THREAD

**Issue by cforce** [reubenmallaby/redmine_projects_accordion#1]
Can u please upload some screeners or even a demo site where this is shown. Tx.

**Comment by reubenmallaby** [comment]
I'm currently running some internal trials - I'll add them to a web-visible site ASAP!

**Comment by reubenmallaby** [comment]
I've just set this up at http://redmine.mallaby.me/projects

**Comment by cforce** [comment]
Tx for this.

**Comment by reubenmallaby** [comment]
Screenshot: http://redmine.mallaby.me/attachments/download/2/bootstrap.png

Demo:

http://redmine.mallaby.me/projects/redmine_bootstrap

**Comment by cforce** [comment]
Can u please publsih this theme, looks very nice ;)

**Comment by reubenmallaby** [comment]
It's in https://github.com/reubenmallaby/redmine_bootstrap 8) Still needs work though!
