### ISSUE TITLE
Accodrion closes all leaves if i click leaf project 

### ISSUE THREAD

**Issue by cforce** [reubenmallaby/redmine_projects_accordion#3]
All is collapsed i i click any project on bottom tree level.

**Comment by cforce** [comment]
Using Firefox

**Comment by reubenmallaby** [comment]
Noticed the same - it doesn't do the same on a separate instance of the install but I'll look into it!

**Comment by reubenmallaby** [comment]
Multiple sub-levels seems to work fine (check updated project on my Redmine) let me know if it doesn't work for you.

It seems that when there is only one sub-level that the error occurs.

**Comment by reubenmallaby** [comment]
Updated from Redmine 2.1.2 and jQuery UI. Let me know if you still have problems.

**Comment by reubenmallaby** [comment]
Latest commit allows clicking on the project name to go to the project and has the correct star icon for projects of which the user is a member.
