### ISSUE TITLE
Redmine 2.1.X compatibility

### ISSUE THREAD

**Issue by jolmom** [reubenmallaby/redmine_projects_accordion#4]
The plugin does not work in Redmine 2.1.2.
Thanks
Regards

**Comment by jeick** [comment]
I can second this. The projects do not "accordion", and instead stay static.

**Comment by reubenmallaby** [comment]
Thanks for the notification - I haven't been able to do much recently. The latest version should use the jQuery UI accordion although the styling needs some work and icons for member or closed project.

**Comment by reubenmallaby** [comment]
Latest commit allows clicking on the project name to go to the project and has the correct star icon for projects of which the user is a member.
