### ISSUE TITLE
Visibility only enforced at root

### ISSUE THREAD

**Issue by shwaffles** [reubenmallaby/redmine_projects_accordion#5]
For the first level of the tree in a project list, projects are only shown if they're visible to the user. However, if you expand the list into subprojects, visibility isn't a factor and all subprojects are shown, whether or not the user is allowed to see them.

If I had the time, I'd look into the code and suggest a fix, but I'm pretty limited at the moment. I may followup.

_Followup_
So I had the time. I'm not a skilled coder by any means, but the following seems to resolve my issue. It's an update to app/views/projects/_list.html.erb, line 11:

<%= render :partial => "list", :locals => { :project => child } if child.visible? %>

Really, just changing what was formerly "child.active" to "child.visible". It continues to only show active projects, and regular users will always only see projects they are members of, while admin users will see all active projects, member or not (just like with default Redmine).

**Comment by reubenmallaby** [comment]
Thanks for pointing this out. I have applied your suggestion. Let me know if you find anything else 8)
